
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aksha
 */
public class Home extends javax.swing.JFrame { 
    public int h=0; 
    public int i=0; 
    public int j=0; 
    public int k=0; 
    public int l=0; 
    public int m=0; 
    
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents(); 
        BdelApt.setVisible(false);
        BdelDen.setVisible(false);
       // BdelInst.setVisible(false);
        BdelPT.setVisible(false);
       // BdelPay.setVisible(false);
       // BdelTrt.setVisible(false);
        BdetApt.setVisible(false);
        BdetDen.setVisible(false);
       // BdetInst.setVisible(false);
        BdetPay.setVisible(false);
        BdtPT.setVisible(false);
        BdetTRt.setVisible(false);
        BnApt.setVisible(false);
        BnDen.setVisible(false);
       // BnInst.setVisible(false);
        BnPay.setVisible(false);
        BnTrt.setVisible(false);
        BnewPt.setVisible(false);
        BupApt.setVisible(false);
        BupDen.setVisible(false);
       // BupInst.setVisible(false);
       // BupPay.setVisible(false);
        BupPt.setVisible(false);
        Trtupdate.setVisible(false);
        
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        labtrtupdate.setVisible(false);
        jLabel17.setVisible(false);
        //jLabel18.setVisible(false);
        jLabel19.setVisible(false);
       // jLabel20.setVisible(false);
        jLabel21.setVisible(false);
       // jLabel22.setVisible(false);
       // jLabel23.setVisible(false);
       // jLabel24.setVisible(false);
        //jLabel25.setVisible(false);
       // jLabel26.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPatient = new javax.swing.JButton();
        BnewPt = new javax.swing.JButton();
        BdtPT = new javax.swing.JButton();
        BdelPT = new javax.swing.JButton();
        JBclose = new javax.swing.JButton();
        JBlogout = new javax.swing.JButton();
        LOGOUT = new javax.swing.JLabel();
        CLOSE = new javax.swing.JLabel();
        BupPt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BnDen = new javax.swing.JButton();
        BupDen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BdetDen = new javax.swing.JButton();
        BnApt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        BupApt = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        BdetApt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        BdelApt = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        BdetTRt = new javax.swing.JButton();
        BdelDen = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BnTrt = new javax.swing.JButton();
        BnPay = new javax.swing.JButton();
        BdetPay = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        PATIENT = new javax.swing.JLabel();
        BAppointment = new javax.swing.JButton();
        APPOINTMENT = new javax.swing.JLabel();
        BPayment = new javax.swing.JButton();
        PAYMENT = new javax.swing.JLabel();
        Bdentist = new javax.swing.JButton();
        Btreatement = new javax.swing.JButton();
        DENTIST = new javax.swing.JLabel();
        TREATMENT = new javax.swing.JLabel();
        labtrtupdate = new javax.swing.JLabel();
        Trtupdate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BPatient.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Pat\\Patient.jpg")); // NOI18N
        BPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BPatientMouseClicked(evt);
            }
        });
        BPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPatientActionPerformed(evt);
            }
        });
        getContentPane().add(BPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 70, 81));

        BnewPt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Pat\\NewPatient.jpg")); // NOI18N
        BnewPt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BnewPtComponentShown(evt);
            }
        });
        BnewPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnewPtActionPerformed(evt);
            }
        });
        getContentPane().add(BnewPt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 80, 80));

        BdtPT.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Pat\\pdet.jpeg")); // NOI18N
        BdtPT.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BdtPTComponentShown(evt);
            }
        });
        BdtPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdtPTActionPerformed(evt);
            }
        });
        getContentPane().add(BdtPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 80, 80));

        BdelPT.setText("delt patient");
        BdelPT.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BdelPTComponentShown(evt);
            }
        });
        BdelPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdelPTActionPerformed(evt);
            }
        });
        getContentPane().add(BdelPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 80, 50));

        JBclose.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\db_min_pic\\Close.png")); // NOI18N
        JBclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcloseActionPerformed(evt);
            }
        });
        getContentPane().add(JBclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 81, 70));

        JBlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\db_min_pic\\logout.png")); // NOI18N
        JBlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBlogoutActionPerformed(evt);
            }
        });
        getContentPane().add(JBlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 71, 70));

        LOGOUT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LOGOUT.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUT.setText("Log Out");
        getContentPane().add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 83, -1));

        CLOSE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CLOSE.setForeground(new java.awt.Color(255, 255, 255));
        CLOSE.setText("Close");
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 70, -1));

        BupPt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Pat\\ModifyPatient.jpg")); // NOI18N
        BupPt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BupPtComponentShown(evt);
            }
        });
        BupPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupPtActionPerformed(evt);
            }
        });
        getContentPane().add(BupPt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 80, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Patient");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patient details");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Delete Patient");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, 73, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Update patient");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Dentist");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 96, -1));

        BnDen.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Doc\\newDentist.jpeg")); // NOI18N
        BnDen.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BnDenComponentShown(evt);
            }
        });
        BnDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnDenActionPerformed(evt);
            }
        });
        getContentPane().add(BnDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 80, 80));

        BupDen.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Doc\\UpdateDoc.jpeg")); // NOI18N
        BupDen.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BupDenComponentShown(evt);
            }
        });
        BupDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupDenActionPerformed(evt);
            }
        });
        getContentPane().add(BupDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 80, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update dentist");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 110, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dentist Details");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, -1, -1));

        BdetDen.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Doc\\dentistdetail.jpeg")); // NOI18N
        BdetDen.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BdetDenComponentShown(evt);
            }
        });
        BdetDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdetDenActionPerformed(evt);
            }
        });
        getContentPane().add(BdetDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 80, 80));

        BnApt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Appt\\newAppt.jpg")); // NOI18N
        BnApt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BnAptComponentShown(evt);
            }
        });
        BnApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnAptActionPerformed(evt);
            }
        });
        getContentPane().add(BnApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 80, 80));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("New Appointment");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 120, 30));

        BupApt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Appt\\UpdateAppt.jpg")); // NOI18N
        BupApt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BupAptComponentShown(evt);
            }
        });
        BupApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupAptActionPerformed(evt);
            }
        });
        getContentPane().add(BupApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 80, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Modify  appointment");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 140, 30));

        BdetApt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Appt\\ApptDetails.jpg")); // NOI18N
        BdetApt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BdetAptComponentShown(evt);
            }
        });
        BdetApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdetAptActionPerformed(evt);
            }
        });
        getContentPane().add(BdetApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 80, 80));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Appointment Details");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 130, -1));

        BdelApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdelAptActionPerformed(evt);
            }
        });
        getContentPane().add(BdelApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 670, 80, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Delete Appointment");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 730, 130, -1));

        BdetTRt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Trtmnt\\treatdetails.jpeg")); // NOI18N
        BdetTRt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BdetTRtComponentShown(evt);
            }
        });
        BdetTRt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdetTRtActionPerformed(evt);
            }
        });
        getContentPane().add(BdetTRt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 420, 80, 80));

        BdelDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdelDenActionPerformed(evt);
            }
        });
        getContentPane().add(BdelDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 690, 80, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Delete Detist");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 750, 80, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("New treatment");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 140, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Treatment Details");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 510, 110, 20));

        BnTrt.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Trtmnt\\new Trtment.jpeg")); // NOI18N
        BnTrt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BnTrtComponentShown(evt);
            }
        });
        BnTrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnTrtActionPerformed(evt);
            }
        });
        getContentPane().add(BnTrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 80, 80));

        BnPay.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Payment\\New PAyment.jpeg")); // NOI18N
        BnPay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BnPayComponentShown(evt);
            }
        });
        BnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnPayActionPerformed(evt);
            }
        });
        getContentPane().add(BnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 80, 80));

        BdetPay.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Payment\\details.jpeg")); // NOI18N
        BdetPay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                BdetPayComponentShown(evt);
            }
        });
        BdetPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdetPayActionPerformed(evt);
            }
        });
        getContentPane().add(BdetPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 80, 80));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("New payment");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 120, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Payment Details");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 110, -1));

        PATIENT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PATIENT.setForeground(new java.awt.Color(255, 255, 255));
        PATIENT.setText("Patient");
        getContentPane().add(PATIENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        BAppointment.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Appt\\Appointment.jpg")); // NOI18N
        BAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BAppointmentMouseClicked(evt);
            }
        });
        BAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(BAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 70, 80));

        APPOINTMENT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        APPOINTMENT.setForeground(new java.awt.Color(255, 255, 255));
        APPOINTMENT.setText("Appointment");
        getContentPane().add(APPOINTMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        BPayment.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Payment\\Payment.jpeg")); // NOI18N
        BPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BPaymentMouseClicked(evt);
            }
        });
        getContentPane().add(BPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 80, 80));

        PAYMENT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PAYMENT.setForeground(new java.awt.Color(255, 255, 255));
        PAYMENT.setText("Payment");
        getContentPane().add(PAYMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        Bdentist.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\WhatsApp Image 2022-02-02 at 10.02.52 AM.jpeg")); // NOI18N
        Bdentist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BdentistMouseClicked(evt);
            }
        });
        Bdentist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdentistActionPerformed(evt);
            }
        });
        getContentPane().add(Bdentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 80, 80));

        Btreatement.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Trtmnt\\Treatment.jpeg")); // NOI18N
        Btreatement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtreatementMouseClicked(evt);
            }
        });
        Btreatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtreatementActionPerformed(evt);
            }
        });
        getContentPane().add(Btreatement, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 80, 80));

        DENTIST.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DENTIST.setForeground(new java.awt.Color(255, 255, 255));
        DENTIST.setText("Dentist");
        getContentPane().add(DENTIST, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        TREATMENT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TREATMENT.setForeground(new java.awt.Color(255, 255, 255));
        TREATMENT.setText("Treatment");
        getContentPane().add(TREATMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 70, -1));

        labtrtupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labtrtupdate.setForeground(new java.awt.Color(255, 255, 255));
        labtrtupdate.setText("Update Treatment");
        getContentPane().add(labtrtupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, -1, -1));

        Trtupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\Trtmnt\\updatetreat.jpeg")); // NOI18N
        Trtupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrtupdateActionPerformed(evt);
            }
        });
        getContentPane().add(Trtupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 80, 80));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 262, 1160, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\HomeBakGrd (2).png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBlogoutActionPerformed
        // TODO add your handling code here: 
        int a = JOptionPane.showConfirmDialog(null,"Do you want to log out","Select",JOptionPane.YES_NO_OPTION); 
        if(a==0)
        { 
            setVisible(false); 
            new login().setVisible(true);
        }
            
    }//GEN-LAST:event_JBlogoutActionPerformed

    private void JBcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcloseActionPerformed
        // TODO add your handling code here: 
        int a = JOptionPane.showConfirmDialog(null,"Do you want to log out","Select",JOptionPane.YES_NO_OPTION); 
        if(a==0)
        { 
            System.exit(0);
        }
    }//GEN-LAST:event_JBcloseActionPerformed

    private void BPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPatientActionPerformed

    private void BPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPatientMouseClicked
        // TODO add your handling code here:  
        if(h==0)
        { 
            try{  
                Thread.sleep(250); 
                BnewPt.setVisible(true);
                jLabel3.setVisible(true);
            } 
            catch(Exception e)
            {
                
            }
            
        } 
        else 
        { 
            BnewPt.setVisible(false);
            jLabel3.setVisible(false);
            BupPt.setVisible(false);
            jLabel6.setVisible((false));
            BdtPT.setVisible(false); 
            jLabel4.setVisible(false); 
            BdelPT.setVisible(false);
            jLabel5.setVisible(false); 
            h=0;
            
        }
        
    }//GEN-LAST:event_BPatientMouseClicked

    private void BnAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnAptActionPerformed
        // TODO add your handling code here: 
         new NewAppointment().setVisible(true);
    }//GEN-LAST:event_BnAptActionPerformed

    private void BupAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupAptActionPerformed
        // TODO add your handling code here: 
         new UpdateAppointment().setVisible(true);
    }//GEN-LAST:event_BupAptActionPerformed

    private void BdelAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdelAptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BdelAptActionPerformed

    private void BdelPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdelPTActionPerformed
        // TODO add your handling code here: 
         new DeletePatient().setVisible(true);
    }//GEN-LAST:event_BdelPTActionPerformed

    private void BdelDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdelDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BdelDenActionPerformed

    private void BdetTRtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdetTRtActionPerformed
        // TODO add your handling code here: 
        new TreatmentDetails().setVisible(true);
    }//GEN-LAST:event_BdetTRtActionPerformed

    private void BnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnPayActionPerformed
        // TODO add your handling code here: 
         new NewPayment().setVisible(true);
    }//GEN-LAST:event_BnPayActionPerformed

    private void BnewPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnewPtActionPerformed
        // TODO add your handling code here: 
        new NewPatient().setVisible(true);
    }//GEN-LAST:event_BnewPtActionPerformed

    private void BdetDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdetDenActionPerformed
        // TODO add your handling code here: 
        new DentistDetails().setVisible(true);
    }//GEN-LAST:event_BdetDenActionPerformed

    private void BtreatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtreatementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtreatementActionPerformed

    private void BAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAppointmentActionPerformed
        // TODO add your handling code here: 
        
    }//GEN-LAST:event_BAppointmentActionPerformed

    private void BupDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupDenActionPerformed
        // TODO add your handling code here: 
         new UpdateDentist().setVisible(true);
    }//GEN-LAST:event_BupDenActionPerformed

    private void BnewPtComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BnewPtComponentShown
        // TODO add your handling code here: 
         try{  
                Thread.sleep(250); 
            BupPt.setVisible(true);
            jLabel6.setVisible((true));
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BnewPtComponentShown

    private void BupPtComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BupPtComponentShown
        // TODO add your handling code here: 
        try{  
                Thread.sleep(250); 
           BdtPT.setVisible(true); 
            jLabel4.setVisible(true);
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BupPtComponentShown

    private void BdelPTComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BdelPTComponentShown
        // TODO add your handling code here: 
        try{  
                Thread.sleep(250); 
            BdelPT.setVisible(true);
            jLabel5.setVisible(true); 
            h=1;
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BdelPTComponentShown

    private void BAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAppointmentMouseClicked
        // TODO add your handling code here: 
        if(i==0)
        { 
            try{  
                Thread.sleep(250); 
                BnApt.setVisible(true);
                jLabel10.setVisible(true);
            } 
            catch(Exception e)
            {
                
            }
            
        } 
        else 
        { 
            BnApt.setVisible(false);
            jLabel10.setVisible(false);
            BupApt.setVisible(false);
            jLabel11.setVisible((false));
            BdetApt.setVisible(false); 
            jLabel12.setVisible(false); 
            BdelApt.setVisible(false);
            jLabel13.setVisible(false); 
            i=0;
            
        }
        
    }//GEN-LAST:event_BAppointmentMouseClicked

    private void BnAptComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BnAptComponentShown
        // TODO add your handling code here: 
        try{  
                Thread.sleep(250); 
               BupApt.setVisible(true);
            jLabel11.setVisible((true));
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BnAptComponentShown

    private void BupAptComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BupAptComponentShown
        // TODO add your handling code here: 
         try{  
                Thread.sleep(250); 
               BdetApt.setVisible(true); 
            jLabel12.setVisible(true); 
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BupAptComponentShown

    private void BdetAptComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BdetAptComponentShown
        // TODO add your handling code here: 
         //try{  
           //     Thread.sleep(250); 
             //   BdelApt.setVisible(true);
            //jLabel13.setVisible(true); 
            i=1;
           // } 
            //catch(Exception e)
           //{
                
           // }
    }//GEN-LAST:event_BdetAptComponentShown

    private void BPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPaymentMouseClicked
        // TODO add your handling code here: 
        if(j==0)
        { 
            try{  
                Thread.sleep(250); 
                BnPay.setVisible(true);
                jLabel19.setVisible(true);
            } 
            catch(Exception e)
            {
                
            }
            
        } 
        else 
        { 
            BnPay.setVisible(false);
            jLabel19.setVisible(false);
            //BupPay.setVisible(false);
            //jLabel20.setVisible((false));
            BdetPay.setVisible(false); 
            jLabel21.setVisible(false); 
            //BdelPay.setVisible(false);
            //jLabel22.setVisible(false); 
            j=0;
            
        }
    }//GEN-LAST:event_BPaymentMouseClicked

    private void BnPayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BnPayComponentShown
        // TODO add your handling code here: 
         try{  
                Thread.sleep(250); 
                BdetPay.setVisible(true);
            jLabel21.setVisible((true)); 
            j=1;
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BnPayComponentShown

    private void BdetPayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BdetPayComponentShown
        // TODO add your handling code here: 
         //try{  
                //Thread.sleep(250); 
                // BdelPay.setVisible(true);
            /*jLabel22.setVisible(true); 
            j=1;
            } 
            catch(Exception e)
            {
                
            }*/
    }//GEN-LAST:event_BdetPayComponentShown

    private void BdentistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BdentistMouseClicked
        // TODO add your handling code here:
         if(k==0)
        { 
            try{  
                Thread.sleep(250); 
                 BnDen.setVisible(true);
            jLabel7.setVisible(true);
            } 
            catch(Exception e)
            {
                
            }
            
        } 
        else 
        { 
            BnDen.setVisible(false);
            jLabel7.setVisible(false);
            BupDen.setVisible(false);
            jLabel8.setVisible((false));
            BdetDen.setVisible(false); 
            jLabel9.setVisible(false); 
            BdelDen.setVisible(false);
            jLabel14.setVisible(false); 
            k=0;
            
        }           
    }//GEN-LAST:event_BdentistMouseClicked

    private void BnDenComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BnDenComponentShown
        // TODO add your handling code here: 
         try{  
                Thread.sleep(250); 
                 BupDen.setVisible(true);
            jLabel8.setVisible((true));
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BnDenComponentShown

    private void BupDenComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BupDenComponentShown
        // TODO add your handling code here: 
         try{  
                Thread.sleep(250); 
                 BdetDen.setVisible(true); 
            jLabel9.setVisible(true); 
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BupDenComponentShown

    private void BdetDenComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BdetDenComponentShown
        // TODO add your handling code here: 
        // try{  
              //  Thread.sleep(250); 
           //      BdelDen.setVisible(true);
           // jLabel14.setVisible(true); 
            k=1;
           // } 
           // catch(Exception e)
           // {
                
           // }
    }//GEN-LAST:event_BdetDenComponentShown

    private void BtreatementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtreatementMouseClicked
        // TODO add your handling code here:  
         if(l==0)
        { 
            try{  
                Thread.sleep(250); 
                 BnTrt.setVisible(true);
            jLabel15.setVisible(true);
            } 
            catch(Exception e)
            {
                
            }
            
        } 
        else 
        { 
            BnTrt.setVisible(false);
            jLabel15.setVisible(false);
           Trtupdate.setVisible(false);
           labtrtupdate.setVisible((false));
            BdetTRt.setVisible(false); 
            jLabel17.setVisible(false); 
           // BdelTrt.setVisible(false);
            //jLabel18.setVisible(false); 
            l=0;
            
        }      
        
    }//GEN-LAST:event_BtreatementMouseClicked

    private void BnTrtComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BnTrtComponentShown
        // TODO add your handling code here:
         try{  
                Thread.sleep(250); 
                  BdetTRt.setVisible(true);
            jLabel17.setVisible((true)); 
            
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BnTrtComponentShown

    private void BdetTRtComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BdetTRtComponentShown
        // TODO add your handling code here:
         try{  
                Thread.sleep(250); 
                Trtupdate.setVisible(true);
            labtrtupdate.setVisible(true); 
            l=1;
            } 
            catch(Exception e)
            {
                
            }
    }//GEN-LAST:event_BdetTRtComponentShown

    private void BupPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupPtActionPerformed
        // TODO add your handling code here:  
         new UpdatePatient().setVisible(true);
        
    }//GEN-LAST:event_BupPtActionPerformed

    private void BnTrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnTrtActionPerformed
        // TODO add your handling code here: 
         new NewTreatment().setVisible(true);
    }//GEN-LAST:event_BnTrtActionPerformed

    private void BnDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnDenActionPerformed
        // TODO add your handling code here: 
         new NewDentist().setVisible(true);
    }//GEN-LAST:event_BnDenActionPerformed

    private void TrtupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrtupdateActionPerformed
        // TODO add your handling code here: 
         new UpdateTreatment().setVisible(true);
    }//GEN-LAST:event_TrtupdateActionPerformed

    private void BdtPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdtPTActionPerformed
        // TODO add your handling code here:
        new PatientDetails().setVisible(true);
    }//GEN-LAST:event_BdtPTActionPerformed

    private void BdtPTComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_BdtPTComponentShown
        // TODO add your handling code here:
       // try{
         //   Thread.sleep(250);
           // BdelPT.setVisible(true);
            //jLabel5.setVisible(true);
            h=1;
       // }
        //catch(Exception e)
       // {

        //}
    }//GEN-LAST:event_BdtPTComponentShown

    private void BdetPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdetPayActionPerformed
        // TODO add your handling code here: 
        new Paymentdetails().setVisible(true);
        
    }//GEN-LAST:event_BdetPayActionPerformed

    private void BdetAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdetAptActionPerformed
        // TODO add your handling code here: 
        new AppointmentDetails().setVisible(true);
    }//GEN-LAST:event_BdetAptActionPerformed

    private void BdentistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdentistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BdentistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APPOINTMENT;
    private javax.swing.JButton BAppointment;
    private javax.swing.JButton BPatient;
    private javax.swing.JButton BPayment;
    private javax.swing.JButton BdelApt;
    private javax.swing.JButton BdelDen;
    private javax.swing.JButton BdelPT;
    private javax.swing.JButton Bdentist;
    private javax.swing.JButton BdetApt;
    private javax.swing.JButton BdetDen;
    private javax.swing.JButton BdetPay;
    private javax.swing.JButton BdetTRt;
    private javax.swing.JButton BdtPT;
    private javax.swing.JButton BnApt;
    private javax.swing.JButton BnDen;
    private javax.swing.JButton BnPay;
    private javax.swing.JButton BnTrt;
    private javax.swing.JButton BnewPt;
    private javax.swing.JButton Btreatement;
    private javax.swing.JButton BupApt;
    private javax.swing.JButton BupDen;
    private javax.swing.JButton BupPt;
    private javax.swing.JLabel CLOSE;
    private javax.swing.JLabel DENTIST;
    private javax.swing.JButton JBclose;
    private javax.swing.JButton JBlogout;
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel PATIENT;
    private javax.swing.JLabel PAYMENT;
    private javax.swing.JLabel TREATMENT;
    private javax.swing.JButton Trtupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labtrtupdate;
    // End of variables declaration//GEN-END:variables
}
