
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aksha
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Tusername = new javax.swing.JTextField();
        Bshowpwd = new javax.swing.JCheckBox();
        Blogin = new javax.swing.JButton();
        Bclose = new javax.swing.JButton();
        Jpwd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setText("User Name");
        getContentPane().add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 120, -1));

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password ");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 120, -1));

        Tusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 204, -1));

        Bshowpwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bshowpwd.setText("Show Password");
        Bshowpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BshowpwdActionPerformed(evt);
            }
        });
        getContentPane().add(Bshowpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 204, -1));

        Blogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Blogin.setText("Login");
        Blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloginActionPerformed(evt);
            }
        });
        getContentPane().add(Blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 73, -1));

        Bclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bclose.setText("Close");
        Bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcloseActionPerformed(evt);
            }
        });
        getContentPane().add(Bclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 73, -1));

        Jpwd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jpwd.setCaretColor(new java.awt.Color(240, 240, 240));
        Jpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpwdActionPerformed(evt);
            }
        });
        getContentPane().add(Jpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 200, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 160, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Pictures\\MiniPics\\login2.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloginActionPerformed
        // TODO add your handling code here:  
        String name  = Tusername.getText();
        String pwd = Jpwd.getText();
        
        try {
            Connection con = ConnectionProvider.getCon(); 
            Statement st;  
            st = con.createStatement(); 
            ResultSet rs = st.executeQuery("select  * from login where USERNAME='"+name+"'"); 
            if(rs.next()) 
            {
            String passw = rs.getString(5);
            if( pwd.equals(passw))
        { 
            setVisible(false);
            new Home().setVisible(true);
        } }
            else 
            JOptionPane.showMessageDialog(null, "Incorrect Username or password");
            
        } 
        
         catch(Exception e) 
        {  
            JOptionPane.showMessageDialog(null, e);
        }
        
        
            
       
        
        
    }//GEN-LAST:event_BloginActionPerformed

    private void BcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcloseActionPerformed
        // TODO add your handling code here: 
        int a = JOptionPane.showConfirmDialog(null,"Do You want to Quit", "Select", JOptionPane.YES_NO_OPTION); 
        if(a==0)
            System.exit(0);
    }//GEN-LAST:event_BcloseActionPerformed

    private void BshowpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BshowpwdActionPerformed
        // TODO add your handling code here: 
        if(Bshowpwd.isSelected())
        { 
            Jpwd.setEchoChar((char)0);
        } 
        else 
            Jpwd.setEchoChar('*');
    }//GEN-LAST:event_BshowpwdActionPerformed

    private void JpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpwdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        new Registration().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclose;
    private javax.swing.JButton Blogin;
    private javax.swing.JCheckBox Bshowpwd;
    private javax.swing.JPasswordField Jpwd;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField Tusername;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
